### ISSUE TITLE
请问能否提供更为详细的注释？

### ISSUE THREAD

**Issue by linh47** [crosg/FloatMenuSample#22]
感觉代码里的注释略少，有些地方看不懂。

**Comment by ColdBrando** [comment]
近期我抽空把注释写起来吧

**Comment by ColdBrando** [comment]
https://github.com/crosg/FloatMenuSample/blob/master/FloatMenu/src/main/java/com/yw/game/floatmenu/FloatMenu.java 增加了注释，也改了不少代码，原来用java的布局，换成了xml，这样比较好理解，也比较好改
