### ISSUE TITLE
有bug, 详情见gif

### ISSUE THREAD

**Issue by badboy-tian** [crosg/FloatMenuSample#24]
![3](https://cloud.githubusercontent.com/assets/2835129/21228051/4ef7f132-c317-11e6-9dc7-2c349b68eb58.gif)

**Comment by KevinRocka** [comment]
我已经解决咯。

**Comment by badboy-tian** [comment]
楼上怎么解决的

**Comment by fanOfDemo** [comment]
有解决方案的话，可以提一个request过来，我帮合并

**Comment by fanOfDemo** [comment]
近期会有更新，换个思路解决这个问题

**Comment by badboy-tian** [comment]
可以, 多谢

2016-12-22 13:32 GMT+08:00 wengyiming <notifications@github.com>:

**Comment by ColdBrando** [comment]
@tianqiujie 上图中的BUG主要原因是因为所有的窗口大小都是不确定的，当动态刷新的时候所有的视图都触发了layout，菜单linearLayout GONE时，windowsManger的params的Gravity初始值是LEFT。

**Comment by fanOfDemo** [comment]
解决方法是，当悬浮球在右侧时，将最外层布局固定.可参考我这边的一种实现 ：https://github.com/crosg/FloatMenuSample/commits/master,没有必要写两个，只需要计算好总大小并固定就行

**Comment by protectedMan** [comment]
这个bug还存在啊
