### ISSUE TITLE
可定制化太差，建议可以参考系统dialog的实现，别人用的时候需要大改；

### ISSUE THREAD

**Issue by chenguozhi** [crosg/FloatMenuSample#27]
可定制化太差，建议可以参考系统dialog的实现，别人用的时候需要大改；

**Comment by ColdBrando** [comment]
建议不错，抽空修改下。只封装关键的，其它的留出来自定义，这个issues先留着

**Comment by chenguozhi** [comment]
建议增加addview；提供关键的监听{点击关闭，点击，动画执行结束}；提供是否自动到边框；可xml配置设置动画；大佬，是不是应该这么玩？

**Comment by ColdBrando** [comment]
将核心功能点通过接口的方式暴露出来了，可以参看最新的代码以及readme

**Comment by hydraxman** [comment]
同意同意。写的太初级了，一看就是新手练习作品，junior~本来想借鉴代码，越改越生气，屁都复用不上

**Comment by hydraxman** [comment]
图片全靠bitmap传来传去，一个简单的menu container居然要复写onDraw来实现，服，纯手工啊
