### ISSUE TITLE
MyFloatDialog 的构造方法接收的是个空上下文

### ISSUE THREAD

**Issue by wolf8088521** [crosg/FloatMenuSample#29]
public class MyFloatDialog extends BaseFloatDailog {

    private Activity mContext;

    public MyFloatDialog(Activity context) {
        super(context);
        this.mContext=context;
    }

    @Override
    protected View getLeftView(LayoutInflater inflater, View.OnTouchListener touchListener) {
//        ResourceUtil.getLayoutId(mContext,"layout_menu_left")
//        int identifier = mContext.getResources().getIdentifier("layout_menu_left", "layout",
//                mContext.getPackageName());
//        Log.e(">>>>>>>>>>2>",identifier+">>1>>>");
        Toast.makeText(mContext,"haha",Toast.LENGTH_SHORT).show();//报空指针，是因为没有上下文，是个空引用
        View view = inflater.inflate(R.layout.layout_menu_left, null);
        ImageView leftLogo = (ImageView) view.findViewById(R.id.logo);
        leftLogo.setOnTouchListener(touchListener);
        return view;
    }

**Comment by wolf8088521** [comment]
这个MyFloatDialog我是放到  一个sdk里使用的   对外只要暴露  myFloatDialog = new MyFloatDialog(Main2Activity.this);就行了，但是动态获取资源的时候报空指针了  ，所以toast一下，发现上下文是空的

**Comment by ColdBrando** [comment]
看下最新提交的代码

**Comment by wolf8088521** [comment]
非常感谢  博主！  谢谢博主的修复。      如果作为手游里的悬浮框是不是service更好些。现在这个如果手游里的登录界面弹出来时，悬浮框就没办法操作了。

**Comment by wolf8088521** [comment]
谢谢博主    已经改成服务了

**Comment by ColdBrando** [comment]
是的，一般是在service中启动的。然后根据是否出现在桌面使用不同的window

**Comment by wolf8088521** [comment]
那  悬浮窗打开   ，有提供触摸悬浮窗以外的屏幕，关闭悬浮窗的函数的。
