### ISSUE TITLE
“应用内悬浮窗” 应该 更名为 activity 内悬浮窗吧？ 请问怎么实现 app 内所有界面悬浮窗呢？

### ISSUE THREAD

**Issue by yhaolpz** [crosg/FloatMenuSample#34]

**Comment by ColdBrando** [comment]
退出一个activity的时候销毁之前的，然后使用新的activity重新创建

**Comment by yhaolpz** [comment]
@fanOfDemo  这样在切换的时候控件会闪一下

**Comment by ColdBrando** [comment]
闪一下的问题可以通过优化减少布局耗时，耗时短就看不出来了；当然你也可以使用权限使悬浮控件全局出现，通过app进程退出时手挡关闭避免出现在桌面实现（app内）

**Comment by Richard0403** [comment]
不知道微信读书里面是怎么实现的
