### ISSUE TITLE
请问如何动态改变图标状态呢？

### ISSUE THREAD

**Issue by TennisAndy** [crosg/FloatMenuSample#37]
RT，需要根据不周结果，显示图标不同状态，例如音量小，中，大。请指教

**Comment by ColdBrando** [comment]
如果是网络图片， 建议使用[BaseFloatDailog](https://github.com/crosg/FloatMenuSample/blob/master/FloatMenu/src/main/java/com/yw/game/floatmenu/customfloat/BaseFloatDailog.java) 搭配ImageView自定义悬浮窗，使用图片加载框架动态加载;

如果是本地不同图片，可以动态更新(悬浮球、悬浮菜单、菜单项)对应的模块，或者将旧的悬浮球关闭重新构造新的
